# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
    ]
