# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0002_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='address1',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='address2',
            field=models.CharField(default='', max_length=128),
        ),
    ]
