# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0004_site_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='postal_code',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.CharField(default='', max_length=128),
        ),
    ]
