# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0006_site_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='web_site',
            field=models.URLField(default=''),
        ),
    ]
