# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0007_site_web_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
