# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0008_site_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='city',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='site',
            name='postal_code',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='site',
            name='state',
            field=models.CharField(default='', max_length=32),
        ),
    ]
