# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0009_auto_20160706_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='fax',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='site',
            name='phone',
            field=models.CharField(default='', max_length=32),
        ),
    ]
