# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0010_auto_20160706_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='have_lit',
            field=models.BooleanField(default=False),
        ),
    ]
