# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0011_site_have_lit'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='years_lit',
            field=models.CharField(default='', max_length=128),
        ),
    ]
