# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0012_site_years_lit'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='map_link',
            field=models.URLField(default='', max_length=512),
        ),
    ]
