# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0013_site_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='fee',
            field=models.BooleanField(default=False),
        ),
    ]
