# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0014_site_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='disposition',
            field=models.CharField(choices=[('not_contacted', 'Have not contacted yet'), ('pending', 'Contacted, awaiting a response'), ('responded_lit', 'Responded, and site was lit'), ('responded_declined', 'Responded, but declined to light'), ('no_response', 'No response'), ('contact_failed', 'Unable to contact (email bounced, etc.)')], default='not_contacted', max_length=32),
        ),
    ]
