# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0015_site_disposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='notes',
            field=models.TextField(default=''),
        ),
    ]
