# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0016_site_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='site',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tealdb.Site'),
        ),
    ]
