# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0022_contact_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='', max_length=32),
        ),
    ]
