# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0023_contact_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='country',
            field=models.CharField(default='', max_length=64),
        ),
    ]
