# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0024_contact_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fax',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='contact',
            name='mobile_phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=32),
        ),
    ]
