# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0026_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='social_facebook',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_instagram',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='contact',
            name='social_twitter',
            field=models.CharField(default='', max_length=64),
        ),
    ]
