# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0027_auto_20160706_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='asshole',
            field=models.BooleanField(default=False),
        ),
    ]
