# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0028_contact_asshole'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='official',
            field=models.BooleanField(default=False),
        ),
    ]
