# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-27 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0030_contact_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='lighting_end_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='lighting_start_date',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='site',
            name='submission_date',
            field=models.TextField(default=''),
        ),
    ]
