# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-04 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0031_auto_20161127_0224'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='applied_this_year',
            field=models.BooleanField(default=False),
        ),
    ]
