# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-05 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tealdb', '0032_site_applied_this_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='accepted_this_year',
            field=models.BooleanField(default=False),
        ),
    ]
